### ISSUE TITLE
For all CT Angiography cases, contrast allergy needs to be asked

### ISSUE THREAD

**Issue by avezrizvi** [flexpeace/DI-Testing#13]
CT angiography by the name always suggest the use of contrast. Therefore, it doesn't make sense to say CT angiography with contrast because there is no such thing as an angiography without contrast. Because this is the case, we need to ask about contrast allergy for every angiography study. This needs to be added as an OEF (as with contrast studies) for all angio studies.

**Comment by samibrix** [comment]
this has been added to the CT OEF, please validate. Thanks!

**Comment by genecs88** [comment]
I just checked this by ordering a CT Angio Chest.  All good.
