### ISSUE TITLE
Comment field in vetting to map to general comments ordering field

### ISSUE THREAD

**Issue by avezrizvi** [flexpeace/DI-Testing#17]
We talked about the idea of making the comments field while ordering (e.g. protocol and verification that radiologist spoke to physician) be a part of the vetting pop-up window (where we choose scheduling, contrast allergy, etc).  Ideally, this should be mapped to the general comments during ordering so that technologists are aware there is a pending comment before performing the exam.

**Comment by samibrix** [comment]
Avez, I have tested comments from PowerChart to RDT and from RDT to PowerChart and looks like the comments are flowing as "Special Instructions" from PC to RDT and from RDT to PC as comments if you right click on the exam and pick comments, I can demo that you when I see you next

**Comment by avezrizvi** [comment]
Smail,

The issue isn't whether comments can be seen. The issue is where they are seen. As you know, there a number of "comment" windows during the vetting process. For example, if I decide to replace an exam, the following comments box pops up:

![image](https://cloud.githubusercontent.com/assets/11009123/13139998/9aa026c8-d640-11e5-90e2-3ccddd0608fe.png)

I've added comments here - but where do these comments go? Ideally, the radiologist should document his discussion with a physician AND also any protocol details in this box (as demoed above). In this situation, the tech should then easily be able to pull up these comments during scanning the patients. The "mapping" of this comment field should be in an intuitive location for technologists.  

I explain in detail in person, but this should help better explain this.

**Comment by avezrizvi** [comment]
This was tested via raddesktop under the "protocol" section. If comments are made in the field here, the technologist will see the comment as part of "protocol comments" on the online worklist. It shows up as a comment note. This was tested. Closing out with screenshot below:

![image](https://cloud.githubusercontent.com/assets/11009123/13279253/7290f65c-dae7-11e5-965e-3246c4c5095e.png)
