### ISSUE TITLE
Issue on Order Detail form

### ISSUE THREAD

**Issue by zafar2zafar** [flexpeace/DI-Testing#19]
I hit complete and goes to Order Detail, it asks me for details, I dont want to enter and cancel - but I cant go back and I have to do it. 

![order detail](https://cloud.githubusercontent.com/assets/7323065/12884626/9c9c6c20-ce70-11e5-81e8-af8d1e05f20a.jpg)

**Comment by samibrix** [comment]
The detail the system is asking for are required and it looks like they were missed when ordering so the system will always throw an error message if you try to by pass or cancel. Please fill in the needed required field before submitting. Thanks!
