### ISSUE TITLE
"New line" or "paragraph"

### ISSUE THREAD

**Issue by avezrizvi** [flexpeace/DI-Testing#2]
If you dictate a new line or paragraph in PS360 and sign the report, it doesn't translate to PACS  in the report.

**Comment by genecs88** [comment]
this is an issue that is currently with Paul Marriott's FSI team.  Shyam is working on it.

**Comment by genecs88** [comment]
This is fixed.  Please validate and close.

**Comment by avezrizvi** [comment]
Tested and validated. Closing out.
