### ISSUE TITLE
iSite: US images are not stacking up

### ISSUE THREAD

**Issue by zafar2zafar** [flexpeace/DI-Testing#23]
US machine seems okay as it is sending images as ONE series but we cannot scroll through on iSITE. 
I confirmed number of series by opening the full study in some other viewer and its working fine. 
![20160217_135645](https://cloud.githubusercontent.com/assets/7323065/13108685/c0e278c4-d585-11e5-876c-1993561f0735.jpg)

**Comment by zafar2zafar** [comment]
Avez/Eugene to write email to Philips.

**Comment by genecs88** [comment]
Issue is fixed and confirmed by AVez.  Please close

**Comment by zafar2zafar** [comment]
Issue is resolved.
