### ISSUE TITLE
Double click functionality in Online Worklist

### ISSUE THREAD

**Issue by zafar2zafar** [flexpeace/DI-Testing#24]
Currently double click on any row in online worklist is setup on Details. If you double click, it opens Details. All the details a Tech should know are already in the columns. Is not possible to setup on Exam Management? Might make Tech life easier. At least for those who have been Scheduled for the day (or green). 
Just a thought.

**Comment by samibrix** [comment]
Zafar I'm not sure if I understand your request but are you asking to set up EM to fire from OWL by double clicking on an order instead of the order details?

**Comment by zafar2zafar** [comment]
Yes. Thats what I meant.

**Comment by samibrix** [comment]
I can check and find out

**Comment by zafar2zafar** [comment]
As per Fareed - not possible - as double click functionality is hard coded for Order details. Closing.
