### ISSUE TITLE
Ordering exam in DOE by Radiologist

### ISSUE THREAD

**Issue by zafar2zafar** [flexpeace/DI-Testing#25]
If a radiologist orders an exam (like I did US Face) in DOE, it still goes to Vetting queue. Is it okay? I guess it should land in Online Worklist as Accepted, if orders by Radiologist.

**Comment by izzynel13** [comment]
I'd agree if it was for real time exam as an adjunct to another ongoing but what if the radiologist ordered the ultrasound as a follow-up or to be done after X number of days? In this instance I'd say it needs to flow to scheduling. Comments??

**Comment by genecs88** [comment]
That's not an option. Last we checked, there's no ability "bypass" vetting.
It's all or nothing.

**Comment by samibrix** [comment]
When ordering from DOE regardless of who is ordering the order will always land in the Vetting queue except for XR, I don't think the system is smart enough to know that a radiologist is ordering therefore drops directly to OWL instead of Vetting Tab.

**Comment by zafar2zafar** [comment]
Closing.
