### ISSUE TITLE
I don't have PowerChart access as a Radiologist

### ISSUE THREAD

**Issue by avezrizvi** [flexpeace/DI-Testing#26]
If I load citrix, PROD cerner, App Bar, I cannot load PowerChart. I get the following screenshot error:

![image](https://cloud.githubusercontent.com/assets/11009123/13139587/54a5a1cc-d63e-11e5-9bd5-ecc76e3ac3d6.png)

**Comment by samibrix** [comment]
Can you try this when I'm in OPC to see how you are trying to load PowerChart?

**Comment by schinnagudi** [comment]
Avez,

We are aware of this issue [Impact from CAS Unit Testing] and see the same for different positions.

CAS PowerChart Team is working on the Preferences and will follow up with them ASAP.

Thanks,
Shiva

**Comment by schinnagudi** [comment]
This should be fixed now.

Please Test and let me know..

**Comment by avezrizvi** [comment]
This is now fixed. I'm closing out. Thanks.
