### ISSUE TITLE
Tech's need to be able to vett orders in Online Worklist

### ISSUE THREAD

**Issue by genecs88** [flexpeace/DI-Testing#30]

**Comment by schinnagudi** [comment]
Fareed - Can you log a PR for this?

I can get work with latha to get this done asap.

**Comment by schinnagudi** [comment]
Vetting Privs Tech Changes have been Implemented.

Ready for Testing

**Comment by genecs88** [comment]
Tech's can Vett...But looks like "Communication Type" is not editable...Maybe causing the F error.

**Comment by genecs88** [comment]
resolved and tested.
