### ISSUE TITLE
Patient Registration- seems like further enhancements- Now unable to register

### ISSUE THREAD

**Issue by izzynel13** [flexpeace/DI-Testing#31]
Unable to register now! Go through same steps as usual and end up with dithered add patient'.

![image](https://cloud.githubusercontent.com/assets/17078064/13379009/e3f33ac6-de2a-11e5-9054-e957c66b1652.png)

**Comment by genecs88** [comment]
This is resolved.  Please confirm.

**Comment by izzynel13** [comment]
Confirm resolution of this.
