### ISSUE TITLE
MRI images out of sequence

### ISSUE THREAD

**Issue by genecs88** [flexpeace/DI-Testing#32]

**Comment by genecs88** [comment]
Hi Gene,

The Philips MR Engineer updated the software yesterday afternoon (there was a patch for image stacking in there).  Images were acquired and sent to PACS. The sequencing was fine. This has done what the PACS engineer has suggested in their email.

Thanks for the update from Philips.

We will be doing more imaging and test again to make sure.

David Bowen 
Diagnostic Imaging Project Analyst
PEARL - Patient Electronically Accessible Record for Life

Sidra Medical & Research Center
Qatar Foundation  |  PO Box 26999  |  Doha, Qatar  
Direct +974-44041819 |  Mobile +974-55264322
dbowen@sidra.org  |  www.sidra.org
 
  

From: Eugene Chan 
Sent: Wednesday, March 02, 2016 8:40 AM
To: Zafar Iqbal; Avez Rizvi; David Bowen; Richard Smith
Cc: Fareed Ahmed
Subject: David and Zafar: MRI issue resolved? FW: Case 0106802777 ref:00D301HJhu.500E0UYuo3:ref SID00 - Images not stacking accurately for MR modality 

Hi David and Zafar,

Following up on our chat yesterday…
Did the MRI engineer fix the issue with the images out of sequence?

See comment from  Philips level 2 support below: They’re confirming that PACS is displaying images “as is”.


Thanks,
Eugene

Eugene Chan, PMP, MBA
Project Manager (RIS, PACS, VNA, CVIS, CAMM, Voice Recognition) 
Department of Health Informatics

PEARL - Patient Electronically Accessible Record for Life

Sidra Medical and Research Center
PO Box 26999, Doha, Qatar
Office: +974 4404-6426 |Mobile: +974 6698 7584 | Email echan@sidra.org 
www.sidra.org

Dictated using voice recognition. Please excuse any typographical errors. 


 

From: Clemente, Sergio [mailto:sergio.clemente@philips.com] 
Sent: Tuesday, March 01, 2016 5:45 PM
To: Fareed Ahmed; Afifi, Reem; Pereira, Rohaan; Guha Roy, Amit
Cc: Eugene Chan; Shivakumar Chinnagudi
Subject: Case 0106802777 ref:00D301HJhu.500E0UYuo3:ref SID00 - Images not stacking accurately for MR modality 

Dear Ahmed,

I’ve checked the stacking issue with MRI exams. As you can see in the screenshots below the series are being displayed in the order the MRI sends them to the PACS. 
In a 3rd party (non-Philips) viewer the images in the series display in the same way.

3rd party viewer, 4th image in serie T2W_TSE Sense
 

ISR, 4th image in serie T2W_TSE Sense                                                                                                                                                                                                                                                    
 

As you can see are the X values jumping from positive to negative e.g. left to right. 

 

You can see this when you enable the scout line mode on the localizer and scroll through the series. 
I would ask the head of the MRI department if the scan protocol can be changed or maybe the order of sending on the MRI modality can be changed in a way the radiologists want to see the images. 

Let me know if you would require more information. 

Kind regards / Met vriendelijke groeten / Mit freundlichen Grüßen / Avec mes salutations distinguées / Con mis mejores Saludos/ Con I migliori saluti/ Med venlig hilsen/Nāku noa, nā/ בברכה / Pozdrowienia

Sergio Clemente

Clinical Application Consultant Level 2, Intellispace PACS
Software Customer Services
Enterprise Imaging and Clinical Informatics
Patient Care and Clinical Informatics, Philips Healthcare

Veenpluis 6, Building QV-015
5684 PC Best, The Netherlands

Mobile  : +31 6 2165 9843   
E-mail: sergio.clemente@philips.com
Customer Care: +1 877-328-2808
Customer Care: isitecare@philips.com 

 

Upcoming PTO: -
________________________________________
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by genecs88** [comment]
Please validate.

**Comment by zafar2zafar** [comment]
Problem solved.
