### ISSUE TITLE
Vetting via Rad Desktop

### ISSUE THREAD

**Issue by avezrizvi** [flexpeace/DI-Testing#6]
If you vet an exam using rad desktop, the OEF fields in online vetting worklist do not appear on rad desktop. Hence, you can vet an exam and never answer required OEFs (e.g. contrast allergy?/scheduling).

**Comment by samibrix** [comment]
This should be fixed please validate when you have a chance.

**Comment by avezrizvi** [comment]
This is fixed, retested and confirmed by me. Thanks. Closing out.
