### ISSUE TITLE
Jane cannot access Radnet online worklist

### ISSUE THREAD

**Issue by izzynel13** [flexpeace/DI-Testing#8]
LIKELY related to core permissions.

**Comment by samibrix** [comment]
what user is she using?

**Comment by izzynel13** [comment]
'she' !! is using her own log-in access.

**Comment by samibrix** [comment]
Normally a scheduler doesn't have access to the Online Work List, but in our case the department requested to add the application to the scheduler list of application, let me confirm with Avez/Eugene and make the needed changes. Thanks!

**Comment by genecs88** [comment]
Jane, please test...the changes were made to the Scheduling Clerk role...So this should work for you and any other user with that role.

**Comment by izzynel13** [comment]
@samibrix ,  @genecs88  Still no access- error 29- application not authorized.

![image](https://cloud.githubusercontent.com/assets/17078064/12969433/67fd2130-d091-11e5-8d01-441f8f4f57f8.png)

**Comment by izzynel13** [comment]
checked and ok.
