### ISSUE TITLE
"Start Imaging Department" Entry on Hierarchy is Confusing

### ISSUE THREAD

**Issue by saifrahmed** [flexpeace/DI-Testing#9]
The "Start Imaging Department" leaf on the tree is confusing -- what does it mean?  Does that start the system for our department?

![image001](https://cloud.githubusercontent.com/assets/3844069/12883575/e2557d4e-ce69-11e5-9253-28bd89eca85b.png)

**Comment by samibrix** [comment]
this is the start content that RadNet have built in when first installed, you can ignore that we have that set for testing purposes we will remove it as we get closer to go-live.
